#!/bin/bash
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • DESINSTALAR SCRIPT • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e
sleep 2s
echo -e "\033[42mDESINSTALANDO SCRIPT...\033[0m"
echo -e
sleep 4s
echo -e "\033[42mLIMPANDO TODOS OS ARQUIVOS...\033[0m"
echo -e
sleep 4s
echo -e "\033[42mLIMPANDO LIXO...\033[0m"
sleep 4s
rm -rf start && rm -rf opt_1 && rm -rf opt_2 && rm -rf opt_3 && rm -rf dns_1 && rm -rf dns_2 && rm -rf dns_3 && rm -rf dns_4
clear
echo -e "\E[41;1;37mSCRIPT DESINSTALADO COM SUCESSO! \E[0m"
sleep 4s
clear
exit
