#!/bin/bash
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • DNS PÚBLICOS • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mGOOGLE DNS\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mVOLTAR\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " "
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read options

   case $options in
   (1)
   curl -sO https://raw.githubusercontent.com/Savitar44/dns/main/dns_1 && chmod 777 dns_1 && ./dns_1
   ;;
   (2)
   clear
   echo -e "\033[1;31mRetornando...\033[0m"
   sleep 2s
   curl -sO https://raw.githubusercontent.com/Savitar44/dns/main/start && chmod 777 start && ./start
   ;;
   (*) echo -e "\033[1;31mOpção invalida\033[1;37m"
sleep 2s
echo -e
echo -e "\033[1;31mRetornando...\033[0m"
sleep 2s
curl -sO https://raw.githubusercontent.com/Savitar44/dns/main/opt_3 && chmod 777 opt_3 && ./opt_3

esac
