#!/bin/bash
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • DNS CUSTOMIZADO • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e
echo -e "\033[44mDIGITE SEU DNS : \033[0m"
read DNS
echo -e
echo -e "\033[42mINICIANDO DNS...\033[0m"
ping $DNS
echo -e
echo -e "\033[42mPARANDO DNS...\033[0m"
sleep 2s
clear
echo -e "\033[1;31mRetornando...\033[0m"
sleep 2s
curl -sO https://raw.githubusercontent.com/Savitar44/dns/main/start && chmod 777 start && ./start
