#!/bin/bash
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • DESINSTALAR SCRIPT • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e
sleep 2s
echo -e "\033[44mDESINSTALANDO SCRIPT...\033[0m"
echo -e
sleep 4s
echo -e "\033[44mLIMPANDO TODOS OS ARQUIVOS...\033[0m"
echo -e
sleep 4s
echo -e "\033[44mREMOVENDO LIXO...\033[0m"
sleep 4s
rm -rf start && rm -rf opt_1 && rm -rf opt_2
clear
echo -e "\E[41;1;37mSCRIPT DESINSTALADO COM SUCESSO! \E[0m"
sleep 4s
clear
exit
