#!/bin/bash
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • CONFIGURAÇÕES DE DNS • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mDNS CUSTOMIZADO\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mDESINSTALAR SCRIPT\033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;33mSAIR\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read option

   case $option in
   (1)
   curl -sO https://raw.githubusercontent.com/bot127418/dns/main/opt_1 && chmod 777 opt_1 && ./opt_1
   ;;
   (2)
   curl -sO https://raw.githubusercontent.com/bot127418/dns/main/opt_2 && chmod 777 opt_2 && ./opt_2
   ;;
   (3)
   clear
   echo -e "\033[0;31mSaindo...\033[0m"
   sleep 2s
   clear
   exit
   ;;
   (*) echo -e "\033[1;31mOpção invalida\033[1;37m"
sleep 2s
echo -e
echo -e "\033[1;31mRetornando...\033[0m"
sleep 2s
curl -sO https://raw.githubusercontent.com/bot127418/dns/main/start && chmod 777 start && ./start

esac
